apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-cube-cafe-frontend
  labels:
    app: blue-cube-cafe-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-cube-cafe-frontend
  template:
    metadata:
      labels:
        app: blue-cube-cafe-frontend
    spec:
      containers:
        - name: frontend
          image: adityameshram/react-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
